// 조형민

GET http://localhost:5500/api/jhm/companies?limit=20
###
GET http://localhost:5500/api/companies?orderBy=name

###
GET http://localhost:5500/api/jhm/companies/1c0d70dd-677e-46bc-a863-b746e5e1ff8c

###
GET http://localhost:5500/api/jhm/companies/1dcb892b-e818-4f1b-8f13-7ecf5aaf31d6/rank

###
PATCH  http://localhost:5500/api/jhm/companies/a8b128545-6405-4e82-8282-f0384f2d5f36
Content-Type: application/json

###
GET http://localhost:5500/api/edu/kjy/companies

{
  "mySelectionCount":6
}

###
GET http://localhost:5500/api/kjy/companies/db1a0353-8e84-476c-9b52-53df166a3503


###

GET http://localhost:5500/api/kjy/companies/db1a0353-8e84-476c-9b52-53df166a3503


###
GET http://localhost:5500/api/kjy/companies/db1a0353-8e84-476c-9b52-53df166a3503/investments


###
GET http://localhost:5500/api/khj/companies?limit=10&skip=5